### ISSUE TITLE
Can this compile against latest los20 ?

### ISSUE THREAD

**Issue by Ziggy815** [DeclanShao/android_device_lenovo_TB8703N#1]
Hello,
wow great to see a new dev tree for that old but great device.

can you tell me if that already compiles and works without errors against latest los20 source ?
and how to install after building ? still using the old twrp with sign boot or a new method ?

Greetings
Zig.

**Comment by DeclanShao** [comment]
Hello, there are still many problems at present.

**Comment by DeclanShao** [comment]
The more serious problem is that the camera has a black screen and exits.
There is also the problem of double-clicking to wake up the screen.
Bluetooth seems to disconnect and the system is not very smooth.
Sorry, I'm not a professional developer, so there are some issues that are difficult for me to solve. It is indeed possible to build lineage20 using this device tree, but there are many problems and I do not recommend it. This device tree and kernel refer to redmi note4x. It should be said that it is modified based on note 4x.
@Ziggy815

**Comment by Ziggy815** [comment]
@DeclanShao 
Thanks for the Info, i am also no professional developer but i am willing to help.
How to you flash the Lineageos to the device ? Still using the old twrp from highwaystar or is there a  way to unlock the bootloader in the meantime ?

Greetings
Zig.

**Comment by DeclanShao** [comment]
It seems that by flashing the earliest version of edl mode rom and then unlocking the bootloader, you can get full unlocking.
But it seems to be only for models such as tb8703N and tb8703x. There seems to be some problems with tb8703f.
@Ziggy815

**Comment by Ziggy815** [comment]
seems 8703R also does not work that way :( tried it with  TB-8703X_USR_S000024_161130_ROW_QPST and TB-8703R_USR_S000023_1803121843_Q1241_PRC but does not unlock the bootloader .. well the fastboot oem unlock-go gets  the  "OK" reboots and  is still locked ..

**Comment by DeclanShao** [comment]
However, you can use highwaystar sign-boot patch to solve the problem of booting into 900e.But I don't know if there will be any problem with it working in the android13 4.9 kernel.
@Ziggy815

**Comment by Ziggy815** [comment]
@DeclanShao I played a little around with it,downloaded your compiled version, atm the status from my site is that it cant be installed using the twrp from highwaystar. First problem, there is no vendor partition in the recovery. Second boot sign does not work on the boot.img. 
I will take a look at the recovery, in the next few days maybe it works when i change the kernel in it, but i have not much hope :(

Greetings
Zig.

**Comment by DeclanShao** [comment]
@Ziggy815 
You need to use recovery to flash vendor_1G.zip to create the vendor partition.
After this you need to patch the treble recovery and boot .img and finally flash the treble recovery and lineage rom.

**Comment by DeclanShao** [comment]
[vendor_1G.zip](https://github.com/DeclanShao/android_device_lenovo_TB8703N/files/15064095/vendor_1G.zip)

**Comment by DeclanShao** [comment]
orangefox recovery link https://github.com/DeclanShao/OrangeFox-Action-Builder/releases/download/7859764739/OrangeFox-Unofficial-TB8703N.img

**Comment by DeclanShao** [comment]
sigin-boot  link https://xdaforums.com/t/rom-unofficial-7-1-2-tb8703f-x-r-n-lineageos-14-1-for-lenovo-tab-3-8-plus-p8.3796119/

**Comment by Ziggy815** [comment]
WoW now we are talking :) I will give all that a try tomorrow, just compiling your latest source, will test with it if it runs thru.
@DeclanShao 

Small Update : 

I could compile it, had to comment out a few selinux warnings and your commit with the thermal hal to make it run thru. Also set the selinux to permissive for testing.
Now i get a few hours of sleep and tell you if i could boot and what works here or not :)

**Comment by Ziggy815** [comment]
@DeclanShao 
Here the Update...
Bad news first, my own compiled version gets into bootloop in the lineageos logo. Might be one of the updates since your last compiled version. Will try to check later.
Can you please be so kind and take a look at your local_manifest file if all branches are still the right ones, cause that manifest i used to dl. your code.

Now the good news. Your Version from 18th runs amazingly good. Tried it without gapps for the start.

- Wifi works without any problems, testet with 5GhZ Band had a stable connection of 100Mbit to my Provider. 

- Bluetooth works with a normal Headset und apt-x hd Codec, at least tested it for around 50 minutes without any disconnection. 
Have you had your disconnections with 2.4 or 5GhZ wifi ? Cause 2.4 could cause trouble with using BT.

- Camera does not work, but feels not to be a big issue, more something like the camserver did not start or something..

-OpenGles/Vulkan work both, tested with 3d mark "SlingShot Extreme" runs without any issues speed is almost the same then 
 in my old crDroid Roms for the tab.

Installed Opera and watched a view Videos, 1080p and 720p no freezes in sound or video, sound was over BT

Hope that helps a little. Honestly i am amazed how smooth everthing works for such a early state.

The next idea on my end is to revert my code here back to the 18th so i can compile a version here that works, so i can maybe help you a little more.

But please take a look at the manifest first, not that i am compiling with the wrong revisions.

Greetings
Zig.

**Comment by DeclanShao** [comment]
@Ziggy815 
Do you have any contact information? It’s a bit troublesome to communicate using github.Which country are you from？

**Comment by Ziggy815** [comment]
@DeclanShao 
Yeah thats true :) ziggy815 @ protonmail .com , i am from germany

**Comment by Ziggy815** [comment]
@DeclanShao 

hey :) synced with your latest source + latest los and was able to compile and boot, just had to comment out 2 sepolicies

1. ) #allow ueventd qti_debugfs:dir relabelto;   -   in ueventd.te 
2. ) #allow mm-qcamerad debugfs:file { open read};   -   in mm-qcamerad.te

Looks good so far :)


Greetings
Zig.

**Comment by Ziggy815** [comment]
@DeclanShao 

Hey there, sorry that i did not response earlier but had some private problems... 
So, tested your actual source, everything seems to work now, including the cam. 

One problem i found is that the recording soundlevel seems to be to low, on internal mic and also via bluetooth.

Realy a great work !

Greetings
Zig.

**Comment by DeclanShao** [comment]
@Ziggy815 
There are still some questions
1. Double-click the screen cannot wake it up
2. The color of the LED light is only white. Normally, it should be in multiple colors.
3. Vibrator

**Comment by Ziggy815** [comment]
> @Ziggy815 There are still some questions
> 
> 1. Double-click the screen cannot wake it up
> 2. The color of the LED light is only white. Normally, it should be in multiple colors.
> 3. Vibrator

@DeclanShao 

1. Honestly i have never seen that work in any rom neither the ones from highwaystar nor the crdroid i did a few years ago for this tablet. Maybe it just cant work with the Touchpanel. In my opinion thats not a big problem.

2. Same for this issue, i have never seen the led in another color than white, not even on stock. The brightness should be changeable but i think thats not a multicolor led.

3. That made me wonder cause you had the Vibrator already working if i dont remember completly wrong.

So from my opinion there are two issues that realy worth taking a deeper look, thats the vibrator and that the recording level from the microphone and other inputs are to low.

But honestly even without those two, you did a great job giving life back to this old but great device.

**Comment by DeclanShao** [comment]
@Ziggy815  
In fact, I also want to do 8704X, 8704V, and 8504, but I don’t seem to have that much energy to invest. :smile:
